### ISSUE TITLE
versions for all requirements

### ISSUE THREAD

**Issue by Iddoyadlin** [amir-zeldes/HebPipe#22]
can you state the recommended versions for all packages in requirements.txt?
This will make it easier to make reproducible results.

**Comment by amir-zeldes** [comment]
Mmm, I generally try not to specify all versions too narrowly for people who don't work with venv, since they will get version conflicts that are mostly not actual problems. The tricky ones (torch, tranformers etc.) are already specified - is there a particular dependency that's causing problems for you? I can specify `<=xyz` if there is a specific library whose newest version has breaking changes.
