### ISSUE TITLE
ImportError: cannot import name 'clock' from 'time' (unknown location)

### ISSUE THREAD

**Issue by janihmels** [amir-zeldes/HebPipe#35]
Following `pip install hebpipe` and using the example `python -m hebpipe example_in.txt` I get `ImportError: cannot import name 'clock' from 'time' (unknown location)`.
I am running Python version 3.11

**Comment by amir-zeldes** [comment]
Thanks for reporting. Unfortunately I can't test this under python 3.11, since torch support for 3.11 is [incomplete](https://github.com/pytorch/pytorch/issues/86566) and several dependencies cannot be installed correctly.

However I just tested it under Python 3.9 and it runs fine - can you try a lower version of Python? Once all required libraries have 3.11 binary wheels online I can test 3.11 as well, but I think it's still too new to get into that right now.
